/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkoutsIndexRouteImport } from './routes/workouts/index'
import { Route as WeightIndexRouteImport } from './routes/weight/index'
import { Route as SleepIndexRouteImport } from './routes/sleep/index'
import { Route as NutritionIndexRouteImport } from './routes/nutrition/index'
import { Route as MyLogsIndexRouteImport } from './routes/my-logs/index'
import { Route as ExercisesIndexRouteImport } from './routes/exercises/index'
import { Route as WorkoutsNewRouteImport } from './routes/workouts/new'
import { Route as WorkoutsIdRouteImport } from './routes/workouts/$id'
import { Route as MyLogsNewRouteImport } from './routes/my-logs/new'
import { Route as MyLogsIdRouteImport } from './routes/my-logs/$id'
import { Route as ExercisesNewRouteImport } from './routes/exercises/new'
import { Route as ExercisesIdRouteImport } from './routes/exercises/$id'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutsIndexRoute = WorkoutsIndexRouteImport.update({
  id: '/workouts/',
  path: '/workouts/',
  getParentRoute: () => rootRouteImport,
} as any)
const WeightIndexRoute = WeightIndexRouteImport.update({
  id: '/weight/',
  path: '/weight/',
  getParentRoute: () => rootRouteImport,
} as any)
const SleepIndexRoute = SleepIndexRouteImport.update({
  id: '/sleep/',
  path: '/sleep/',
  getParentRoute: () => rootRouteImport,
} as any)
const NutritionIndexRoute = NutritionIndexRouteImport.update({
  id: '/nutrition/',
  path: '/nutrition/',
  getParentRoute: () => rootRouteImport,
} as any)
const MyLogsIndexRoute = MyLogsIndexRouteImport.update({
  id: '/my-logs/',
  path: '/my-logs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExercisesIndexRoute = ExercisesIndexRouteImport.update({
  id: '/exercises/',
  path: '/exercises/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutsNewRoute = WorkoutsNewRouteImport.update({
  id: '/workouts/new',
  path: '/workouts/new',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutsIdRoute = WorkoutsIdRouteImport.update({
  id: '/workouts/$id',
  path: '/workouts/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MyLogsNewRoute = MyLogsNewRouteImport.update({
  id: '/my-logs/new',
  path: '/my-logs/new',
  getParentRoute: () => rootRouteImport,
} as any)
const MyLogsIdRoute = MyLogsIdRouteImport.update({
  id: '/my-logs/$id',
  path: '/my-logs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ExercisesNewRoute = ExercisesNewRouteImport.update({
  id: '/exercises/new',
  path: '/exercises/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ExercisesIdRoute = ExercisesIdRouteImport.update({
  id: '/exercises/$id',
  path: '/exercises/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/exercises/$id': typeof ExercisesIdRoute
  '/exercises/new': typeof ExercisesNewRoute
  '/my-logs/$id': typeof MyLogsIdRoute
  '/my-logs/new': typeof MyLogsNewRoute
  '/workouts/$id': typeof WorkoutsIdRoute
  '/workouts/new': typeof WorkoutsNewRoute
  '/exercises/': typeof ExercisesIndexRoute
  '/my-logs/': typeof MyLogsIndexRoute
  '/nutrition/': typeof NutritionIndexRoute
  '/sleep/': typeof SleepIndexRoute
  '/weight/': typeof WeightIndexRoute
  '/workouts/': typeof WorkoutsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/exercises/$id': typeof ExercisesIdRoute
  '/exercises/new': typeof ExercisesNewRoute
  '/my-logs/$id': typeof MyLogsIdRoute
  '/my-logs/new': typeof MyLogsNewRoute
  '/workouts/$id': typeof WorkoutsIdRoute
  '/workouts/new': typeof WorkoutsNewRoute
  '/exercises': typeof ExercisesIndexRoute
  '/my-logs': typeof MyLogsIndexRoute
  '/nutrition': typeof NutritionIndexRoute
  '/sleep': typeof SleepIndexRoute
  '/weight': typeof WeightIndexRoute
  '/workouts': typeof WorkoutsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/exercises/$id': typeof ExercisesIdRoute
  '/exercises/new': typeof ExercisesNewRoute
  '/my-logs/$id': typeof MyLogsIdRoute
  '/my-logs/new': typeof MyLogsNewRoute
  '/workouts/$id': typeof WorkoutsIdRoute
  '/workouts/new': typeof WorkoutsNewRoute
  '/exercises/': typeof ExercisesIndexRoute
  '/my-logs/': typeof MyLogsIndexRoute
  '/nutrition/': typeof NutritionIndexRoute
  '/sleep/': typeof SleepIndexRoute
  '/weight/': typeof WeightIndexRoute
  '/workouts/': typeof WorkoutsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/profile'
    | '/register'
    | '/exercises/$id'
    | '/exercises/new'
    | '/my-logs/$id'
    | '/my-logs/new'
    | '/workouts/$id'
    | '/workouts/new'
    | '/exercises/'
    | '/my-logs/'
    | '/nutrition/'
    | '/sleep/'
    | '/weight/'
    | '/workouts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/profile'
    | '/register'
    | '/exercises/$id'
    | '/exercises/new'
    | '/my-logs/$id'
    | '/my-logs/new'
    | '/workouts/$id'
    | '/workouts/new'
    | '/exercises'
    | '/my-logs'
    | '/nutrition'
    | '/sleep'
    | '/weight'
    | '/workouts'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/auth'
    | '/profile'
    | '/register'
    | '/exercises/$id'
    | '/exercises/new'
    | '/my-logs/$id'
    | '/my-logs/new'
    | '/workouts/$id'
    | '/workouts/new'
    | '/exercises/'
    | '/my-logs/'
    | '/nutrition/'
    | '/sleep/'
    | '/weight/'
    | '/workouts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  ExercisesIdRoute: typeof ExercisesIdRoute
  ExercisesNewRoute: typeof ExercisesNewRoute
  MyLogsIdRoute: typeof MyLogsIdRoute
  MyLogsNewRoute: typeof MyLogsNewRoute
  WorkoutsIdRoute: typeof WorkoutsIdRoute
  WorkoutsNewRoute: typeof WorkoutsNewRoute
  ExercisesIndexRoute: typeof ExercisesIndexRoute
  MyLogsIndexRoute: typeof MyLogsIndexRoute
  NutritionIndexRoute: typeof NutritionIndexRoute
  SleepIndexRoute: typeof SleepIndexRoute
  WeightIndexRoute: typeof WeightIndexRoute
  WorkoutsIndexRoute: typeof WorkoutsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workouts/': {
      id: '/workouts/'
      path: '/workouts'
      fullPath: '/workouts/'
      preLoaderRoute: typeof WorkoutsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weight/': {
      id: '/weight/'
      path: '/weight'
      fullPath: '/weight/'
      preLoaderRoute: typeof WeightIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sleep/': {
      id: '/sleep/'
      path: '/sleep'
      fullPath: '/sleep/'
      preLoaderRoute: typeof SleepIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nutrition/': {
      id: '/nutrition/'
      path: '/nutrition'
      fullPath: '/nutrition/'
      preLoaderRoute: typeof NutritionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-logs/': {
      id: '/my-logs/'
      path: '/my-logs'
      fullPath: '/my-logs/'
      preLoaderRoute: typeof MyLogsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises/': {
      id: '/exercises/'
      path: '/exercises'
      fullPath: '/exercises/'
      preLoaderRoute: typeof ExercisesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workouts/new': {
      id: '/workouts/new'
      path: '/workouts/new'
      fullPath: '/workouts/new'
      preLoaderRoute: typeof WorkoutsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workouts/$id': {
      id: '/workouts/$id'
      path: '/workouts/$id'
      fullPath: '/workouts/$id'
      preLoaderRoute: typeof WorkoutsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-logs/new': {
      id: '/my-logs/new'
      path: '/my-logs/new'
      fullPath: '/my-logs/new'
      preLoaderRoute: typeof MyLogsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-logs/$id': {
      id: '/my-logs/$id'
      path: '/my-logs/$id'
      fullPath: '/my-logs/$id'
      preLoaderRoute: typeof MyLogsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises/new': {
      id: '/exercises/new'
      path: '/exercises/new'
      fullPath: '/exercises/new'
      preLoaderRoute: typeof ExercisesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises/$id': {
      id: '/exercises/$id'
      path: '/exercises/$id'
      fullPath: '/exercises/$id'
      preLoaderRoute: typeof ExercisesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  ExercisesIdRoute: ExercisesIdRoute,
  ExercisesNewRoute: ExercisesNewRoute,
  MyLogsIdRoute: MyLogsIdRoute,
  MyLogsNewRoute: MyLogsNewRoute,
  WorkoutsIdRoute: WorkoutsIdRoute,
  WorkoutsNewRoute: WorkoutsNewRoute,
  ExercisesIndexRoute: ExercisesIndexRoute,
  MyLogsIndexRoute: MyLogsIndexRoute,
  NutritionIndexRoute: NutritionIndexRoute,
  SleepIndexRoute: SleepIndexRoute,
  WeightIndexRoute: WeightIndexRoute,
  WorkoutsIndexRoute: WorkoutsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
